loki:
  enabled: true
  isDefault: true
  persistence:
    enabled: true
    storageClassName: manual
    size: 3Gi

promtail:
  enabled: true
  config:
    lokiAddress: http://{{ .Release.Name }}-loki:3100/loki/api/v1/push

grafana:
  enabled: false
  sidecar:
    datasources:
      enabled: true
      maxLines: 1000
  image:
    tag: 8.3.5
