apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Values.global.namespace }}
  name: {{ .Values.deployment.metadata.name }}
  labels:
    app: {{ .Values.deployment.metadata.labels.app }}
spec:
  replicas: {{ .Values.deployment.spec.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.deployment.spec.selector.app }}
  template:
    metadata:
      labels:
        app: {{ .Values.deployment.template.labels.app }}
    spec:
      containers:
      - name: {{ .Values.deployment.container.name }}
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.imagePullPolicy }}
        ports:
        - containerPort: {{ .Values.deployment.container.containerPort }}
