global:
  namespace: cdms
deployment:
  metadata:
    name: cdms-deployment
    labels:
      app: cdms
  spec:
    replicas: 1
    selector:
      app: cdms
  template:
    labels:
      app: cdms
  container:
    name: cdms
    containerPort: 8080

image:
  repository: sarwansharma/cdms
  tag: latest
  imagePullPolicy: Always
  containerPort: 8080

service:
  name: cdms-service
  spec:
    externalPortType: NodePort
    selector:
      app: cdms
  ports:
    name: cdmswebport
    port: 8080
    targetPort: 8080
    externalPort: 31000


