# Default values for minioWebApp.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
deployment:
  metadata:
    name: minio-deployment
    labels:
      app: minio
  spec:
    replicas: 1
    selector:
      app: minio
  template:
    labels:
      app: minio
  container:
    name: minio
    containerPort1: 9000
    containerPort2: 9001

image:
  repository: sarwansharma/minio
  tag: v3
  imagePullPolicy: Always

volume:
  name: minio-storage
  pvc: minio-pvc
  mountPath: "/storage"

####################################

service:
  name: minio-service
  spec:
    externalPortType: NodePort
    selector:
      app: minio
  ports:
    name1: apiport
    port1: 9000
    targetPort1: 9000
    externalPort1: 31002

    name2: webport
    port2: 9001
    targetPort2: 9001
    externalPort2: 31003

####################################

pv:
  name: minio-pv
  type: local
  storageClassName: manual
  capacity: 1Gi
  accessModes: ReadWriteOnce
  path: "/cdmsData/minioData"
  claimRef:
    pvcname: minio-pvc

####################################

pvc:
  name: minio-pvc
  labels:
    app: minio-storage-claim
  storageClassName: manual
  capacity: 1Gi
  accessModes: ReadWriteOnce

