apiVersion: v1
kind: PersistentVolume
metadata:
  name: loki-pv
spec:
  storageClassName: manual
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
  claimRef:
    namespace: monitoring
    name: storage-lpg-stack-loki-0
  hostPath:
    path: "/cdmsData/lokiData"
