apiVersion: apps/v1 #  for k8s versions before 1.9.0 use apps/v1beta2  and before 1.8.0 use extensions/v1beta1
kind: Deployment
metadata:
  # This name uniquely identifies the Deployment
  name: {{ .Values.deployment.metadata.name }}
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ .Values.deployment.metadata.labels.app }}
spec:
  replicas: {{ .Values.deployment.spec.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.deployment.spec.selector.app }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        # Label is used as selector in the service.
        app: {{ .Values.deployment.template.labels.app }}
    spec:
      # Refer to the PVC created earlier
      volumes:
      - name: {{ .Values.volume.name }}
        persistentVolumeClaim:
          # Name of the PVC created earlier
          claimName: {{ .Values.volume.pvc }}
      containers:
      - name: {{ .Values.deployment.container.name }}
        # Pulls the default Minio image from Docker Hub
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.imagePullPolicy }}
        args:
        - server
        - {{ .Values.volume.mountPath }}
        - --console-address 
        - ":{{ .Values.deployment.container.containerPort2 }}"
        env:
        # Minio access key and secret key
        - name: MINIO_ACCESS_KEY
          value: "minioadmin"
        - name: MINIO_SECRET_KEY
          value: "minioadmin"
        ports:
        - containerPort: {{ .Values.deployment.container.containerPort1 }}
        - containerPort: {{ .Values.deployment.container.containerPort2 }}
        # Mount the volume into the pod
        volumeMounts:
        - name: {{ .Values.volume.name }} # must match the volume name, above
          mountPath: {{ .Values.volume.mountPath }}
