apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  namespace: {{ .Values.global.namespace }}
spec:
  type: {{ .Values.service.spec.externalPortType }}
  selector:
    app: {{ .Values.service.spec.selector.app }}
  ports:
      # By default and for convenience, the `targetPort` is set to the same value as the `port` field.
    - name: {{ .Values.service.ports.name1 }}
      port: {{ .Values.service.ports.port1 }}
      targetPort: {{ .Values.service.ports.targetPort1 }}
      protocol: TCP
      # Optional field
      # By default and for convenience, the Kubernetes control plane will allocate a port from a range (default: 30000-32767)
      nodePort: {{ .Values.service.ports.externalPort1 }}
    - name: {{ .Values.service.ports.name2 }}
      port: {{ .Values.service.ports.port2 }}
      targetPort: {{ .Values.service.ports.targetPort2 }}
      protocol: TCP
      # Optional field
      # By default and for convenience, the Kubernetes control plane will allocate a port from a range (default: 30000-32767)
      nodePort: {{ .Values.service.ports.externalPort2 }}
      #
