apiVersion: apps/v1
kind: Deployment
metadata:
    # This name uniquely identifies the Deployment
  name: {{ .Values.deployment.metadata.name }}
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ .Values.deployment.metadata.labels.app }}
spec:
  replicas: {{ .Values.deployment.spec.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.deployment.spec.selector.app }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        # Label is used as selector in the service.
        app: {{ .Values.deployment.template.labels.app }}
    spec:
      # Refer to the PVC created earlier
      containers:
        - name: {{ .Values.deployment.container.name }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          ports:
            - containerPort: {{ .Values.deployment.container.containerPort }}
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret.name }}
                  key: ROOT_PASSWORD
          volumeMounts:
            - name: {{ .Values.volume.name1 }}
              mountPath: {{ .Values.volume.mountPath1 }}
            - mountPath: {{ .Values.volume.mountPath2 }}
              subPath: "mysql"
              name: {{ .Values.volume.name2 }}
      volumes:
        - name: {{ .Values.volume.name1 }}
          configMap:
            name: {{ .Values.volume.configMap1 }}
        - name: {{ .Values.volume.name2 }}
          persistentVolumeClaim:
            claimName: {{ .Values.volume.pvc2 }}
